name: Run SonarCloud on code

on:
  push:
    branches:
      - master


jobs: 
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Restore
      run: dotnet restore
    - name: Install sonarscanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Start Scanner
      run: dotnet sonarscanner begin /k:jlndk_devoops /d:sonar.host.url=https://sonarcloud.io /o:jlndk /d:sonar.login=${{ secrets.SONAR_KEY }}
    - name: Dotnet build
      run: dotnet build --configuration Release
    - name: dotnet test
      run: dotnet test
    - name: Upload sonarcloud report
      run: dotnet sonarscanner end /d:sonar.login=${{ secrets.SONAR_KEY }}